<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-5K9H8Q3R" failures="0" tests="7" name="Demo1.Day2" time="0.010" errors="1" timestamp="2020-07-29T21:48:53 IST" skipped="2">
  <testcase classname="Demo1.Day2" name="catchData" time="0.003"/>
  <testcase classname="Demo1.Day2" name="toInclude5" time="0.001"/>
  <testcase classname="Demo1.Day2" name="toInclude" time="0.000">
    <error message="
Parameter &#039;URL&#039; is required by @Test on method toInclude but has not been marked @Optional or defined
in C:\Users\Lenovo\eclipse-workspace\TestNGTesting\testng1.xml" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Parameter 'URL' is required by @Test on method toInclude but has not been marked @Optional or defined
in C:\Users\Lenovo\eclipse-workspace\TestNGTesting\testng1.xml
at org.testng.internal.Parameters.createParams(Parameters.java:289)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:377)
at org.testng.internal.Parameters.createParameters(Parameters.java:721)
at org.testng.internal.Parameters.handleParameters(Parameters.java:895)
at org.testng.internal.Parameters.handleParameters(Parameters.java:762)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:60)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:39)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:771)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- toInclude -->
  <testcase classname="Demo1.Day2" name="Apanpahile" time="0.002">
    <skipped/>
  </testcase> <!-- Apanpahile -->
  <testcase classname="Demo1.Day2" name="catchData" time="0.002"/>
  <testcase classname="Demo1.Day2" name="catchData" time="0.002"/>
  <testcase classname="Demo1.Day2" name="toInclude3">
    <skipped/>
  </testcase> <!-- toInclude3 -->
</testsuite> <!-- Demo1.Day2 -->
